### ISSUE TITLE
Example not working in VSCodium 1.33.0

### ISSUE THREAD

**Issue by Skeeve** [jeff-hykin/macro-commander#1]
I installed macro-commander and tried to follow the example.

VSC is complaining about the command "macros.exampleMacro1" in the keybindings.

![image](https://user-images.githubusercontent.com/725404/60078700-c28ebb80-972c-11e9-9cfa-88404c80b656.png)

**Comment by jeff-hykin** [comment]
Sadly the green underline is to be expected for now, however the command should still work. (If it does not, please let me know since that would be a bug)

The reason there is a green underline is because VSC uses the extension's `package.json` in order to find out what commands an extension is adding. Well, I can't add the name of a user's command to the package.json because I don't know what they're going to call it. Instead, the command is dynamically generated based on what the user creates. This works at runtime, but VSC doesn't pick up on it.

There are many times this non-dynamic feature causes problems (not on just this extension). It is possible to dynamically find the `package.json` for the extension on the user's computer at runtime, and then add the user command to it, overwrite the existing `package.json`, and then force VSC to reload to pick up on the change, but that would be a very hacky solution. If there's enough extensions that need this kind of feature I might make a tool that simplifies the process. However, there's no universal way of getting around the window reload that would be needed after every new command was added to the setting.json.
